//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DisplayText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About US.
        /// </summary>
        internal static string AboutUS {
            get {
                return ResourceManager.GetString("AboutUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Terms.
        /// </summary>
        internal static string AcceptTerms {
            get {
                return ResourceManager.GetString("AcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Data.
        /// </summary>
        internal static string AddNewData {
            get {
                return ResourceManager.GetString("AddNewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Of Agent.
        /// </summary>
        internal static string AdmistraterOfAgent {
            get {
                return ResourceManager.GetString("AdmistraterOfAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Of Organizer.
        /// </summary>
        internal static string AdmistraterOfOrganizer {
            get {
                return ResourceManager.GetString("AdmistraterOfOrganizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Of Performance Group.
        /// </summary>
        internal static string AdmistraterOfPerformanceGroup {
            get {
                return ResourceManager.GetString("AdmistraterOfPerformanceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Of Promoter.
        /// </summary>
        internal static string AdmistraterOfPromoter {
            get {
                return ResourceManager.GetString("AdmistraterOfPromoter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advisory Members.
        /// </summary>
        internal static string Advisorymembers {
            get {
                return ResourceManager.GetString("Advisorymembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliation.
        /// </summary>
        internal static string Affiliation {
            get {
                return ResourceManager.GetString("Affiliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agora.
        /// </summary>
        internal static string Agora {
            get {
                return ResourceManager.GetString("Agora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        internal static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amature Musician.
        /// </summary>
        internal static string AmatureMusician {
            get {
                return ResourceManager.GetString("AmatureMusician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Center.
        /// </summary>
        internal static string ArchiveCenter {
            get {
                return ResourceManager.GetString("ArchiveCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        internal static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Title.
        /// </summary>
        internal static string ArticleTitle {
            get {
                return ResourceManager.GetString("ArticleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article URL.
        /// </summary>
        internal static string ArticleURL {
            get {
                return ResourceManager.GetString("ArticleURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audition outline and Application Info.
        /// </summary>
        internal static string AuditionOutlineandApplicationInfo {
            get {
                return ResourceManager.GetString("AuditionOutlineandApplicationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditions.
        /// </summary>
        internal static string Auditions {
            get {
                return ResourceManager.GetString("Auditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogger.
        /// </summary>
        internal static string Blogger {
            get {
                return ResourceManager.GetString("Blogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOD Members.
        /// </summary>
        internal static string BODMembers {
            get {
                return ResourceManager.GetString("BODMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO Message.
        /// </summary>
        internal static string CEOMessage {
            get {
                return ResourceManager.GetString("CEOMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Coin.
        /// </summary>
        internal static string ClassicCoin {
            get {
                return ResourceManager.GetString("ClassicCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Mania.
        /// </summary>
        internal static string ClassicMania {
            get {
                return ResourceManager.GetString("ClassicMania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College Photo.
        /// </summary>
        internal static string CollegePhoto {
            get {
                return ResourceManager.GetString("CollegePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Background.
        /// </summary>
        internal static string CompanyBackground {
            get {
                return ResourceManager.GetString("CompanyBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string CompLocation {
            get {
                return ResourceManager.GetString("CompLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer.
        /// </summary>
        internal static string Composer {
            get {
                return ResourceManager.GetString("Composer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concert Venue.
        /// </summary>
        internal static string ConcertVenue {
            get {
                return ResourceManager.GetString("ConcertVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concour Outline.
        /// </summary>
        internal static string ConcourOutline {
            get {
                return ResourceManager.GetString("ConcourOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concours.
        /// </summary>
        internal static string Concours {
            get {
                return ResourceManager.GetString("Concours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductor.
        /// </summary>
        internal static string Conductor {
            get {
                return ResourceManager.GetString("Conductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        internal static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you accept privacy policy ?.
        /// </summary>
        internal static string Doyouacceptprivacypolicy {
            get {
                return ResourceManager.GetString("Doyouacceptprivacypolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you accept terms of use ?.
        /// </summary>
        internal static string Doyouaccepttermsofuse {
            get {
                return ResourceManager.GetString("Doyouaccepttermsofuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorse.
        /// </summary>
        internal static string Endorse {
            get {
                return ResourceManager.GetString("Endorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsed Date.
        /// </summary>
        internal static string EndorsedDate {
            get {
                return ResourceManager.GetString("EndorsedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorser.
        /// </summary>
        internal static string Endorser {
            get {
                return ResourceManager.GetString("Endorser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorser Email ID.
        /// </summary>
        internal static string EndorserEmailID {
            get {
                return ResourceManager.GetString("EndorserEmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorser Name.
        /// </summary>
        internal static string EndorserName {
            get {
                return ResourceManager.GetString("EndorserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expertise.
        /// </summary>
        internal static string Expertise {
            get {
                return ResourceManager.GetString("Expertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook URL.
        /// </summary>
        internal static string FacebookURL {
            get {
                return ResourceManager.GetString("FacebookURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax No.
        /// </summary>
        internal static string FaxNo {
            get {
                return ResourceManager.GetString("FaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot the password?.
        /// </summary>
        internal static string Forgotthepassword {
            get {
                return ResourceManager.GetString("Forgotthepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Type.
        /// </summary>
        internal static string GroupType {
            get {
                return ResourceManager.GetString("GroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry.
        /// </summary>
        internal static string Inquiry {
            get {
                return ResourceManager.GetString("Inquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument.
        /// </summary>
        internal static string Instrument {
            get {
                return ResourceManager.GetString("Instrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        internal static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        internal static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kakao Talk ID.
        /// </summary>
        internal static string KakaoTalkID {
            get {
                return ResourceManager.GetString("KakaoTalkID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KR.
        /// </summary>
        internal static string kr {
            get {
                return ResourceManager.GetString("kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Map.
        /// </summary>
        internal static string LocationMap {
            get {
                return ResourceManager.GetString("LocationMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Instrument.
        /// </summary>
        internal static string MainInstrument {
            get {
                return ResourceManager.GetString("MainInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Title.
        /// </summary>
        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Title Composer.
        /// </summary>
        internal static string MainTitleComposer {
            get {
                return ResourceManager.GetString("MainTitleComposer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        internal static string Major {
            get {
                return ResourceManager.GetString("Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        internal static string MobileNo {
            get {
                return ResourceManager.GetString("MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music College.
        /// </summary>
        internal static string MusicCollegeDB {
            get {
                return ResourceManager.GetString("MusicCollegeDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musician.
        /// </summary>
        internal static string Musician {
            get {
                return ResourceManager.GetString("Musician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musician.
        /// </summary>
        internal static string MusicianDB {
            get {
                return ResourceManager.GetString("MusicianDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Shop.
        /// </summary>
        internal static string MusicShop {
            get {
                return ResourceManager.GetString("MusicShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My page.
        /// </summary>
        internal static string Mypage {
            get {
                return ResourceManager.GetString("Mypage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Data Input Screen.
        /// </summary>
        internal static string NewDataInputScreen {
            get {
                return ResourceManager.GetString("NewDataInputScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Question.
        /// </summary>
        internal static string NewQuestion {
            get {
                return ResourceManager.GetString("NewQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick Name.
        /// </summary>
        internal static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORG.
        /// </summary>
        internal static string ORG {
            get {
                return ResourceManager.GetString("ORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizer.
        /// </summary>
        internal static string Organizer {
            get {
                return ResourceManager.GetString("Organizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other SNS.
        /// </summary>
        internal static string OtherSNS {
            get {
                return ResourceManager.GetString("OtherSNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name.
        /// </summary>
        internal static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        internal static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People &amp; Job.
        /// </summary>
        internal static string PeopleJob {
            get {
                return ResourceManager.GetString("PeopleJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People or Job.
        /// </summary>
        internal static string PeopleOrJob {
            get {
                return ResourceManager.GetString("PeopleOrJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        internal static string PerformanceDB {
            get {
                return ResourceManager.GetString("PerformanceDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Group.
        /// </summary>
        internal static string PerformanceGroup {
            get {
                return ResourceManager.GetString("PerformanceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Schedule.
        /// </summary>
        internal static string Performanceschedule {
            get {
                return ResourceManager.GetString("Performanceschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Type.
        /// </summary>
        internal static string PerformanceType {
            get {
                return ResourceManager.GetString("PerformanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Info.
        /// </summary>
        internal static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo 1.
        /// </summary>
        internal static string Photo1 {
            get {
                return ResourceManager.GetString("Photo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo 2.
        /// </summary>
        internal static string Photo2 {
            get {
                return ResourceManager.GetString("Photo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played by.
        /// </summary>
        internal static string Playedby {
            get {
                return ResourceManager.GetString("Playedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click as many as you think you are!.
        /// </summary>
        internal static string Pleaseclickasmanyasyouthinkyouare {
            get {
                return ResourceManager.GetString("Pleaseclickasmanyasyouthinkyouare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleaseEnterEndDate {
            get {
                return ResourceManager.GetString("PleaseEnterEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleaseEnterMainTitle {
            get {
                return ResourceManager.GetString("PleaseEnterMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleaseEnterStartDate {
            get {
                return ResourceManager.GetString("PleaseEnterStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleaseEnterTicketBoxinfo {
            get {
                return ResourceManager.GetString("PleaseEnterTicketBoxinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleaseEnterTime {
            get {
                return ResourceManager.GetString("PleaseEnterTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleaseenteryourEmail {
            get {
                return ResourceManager.GetString("PleaseenteryourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleaseenteryourFullName {
            get {
                return ResourceManager.GetString("PleaseenteryourFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleaseenteryourPassword {
            get {
                return ResourceManager.GetString("PleaseenteryourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleasefillAddressfield {
            get {
                return ResourceManager.GetString("PleasefillAddressfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleasefillAuditionoutlinefield {
            get {
                return ResourceManager.GetString("PleasefillAuditionoutlinefield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleasefillConcouroutlinefield {
            get {
                return ResourceManager.GetString("PleasefillConcouroutlinefield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleasefillContactNamefield {
            get {
                return ResourceManager.GetString("PleasefillContactNamefield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleasefillDescriptionfield {
            get {
                return ResourceManager.GetString("PleasefillDescriptionfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleasefillEmailfield {
            get {
                return ResourceManager.GetString("PleasefillEmailfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string Pleasefillorganizerfield {
            get {
                return ResourceManager.GetString("Pleasefillorganizerfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleasefillPerformanceGroupfield {
            get {
                return ResourceManager.GetString("PleasefillPerformanceGroupfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleasefillSinceYearfield {
            get {
                return ResourceManager.GetString("PleasefillSinceYearfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleasefillTelNofield {
            get {
                return ResourceManager.GetString("PleasefillTelNofield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string Pleasefillthearticletitle {
            get {
                return ResourceManager.GetString("Pleasefillthearticletitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleasefillthearticleURL {
            get {
                return ResourceManager.GetString("PleasefillthearticleURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string Pleasefillthecountryfield {
            get {
                return ResourceManager.GetString("Pleasefillthecountryfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleasefilltheHomepagefield {
            get {
                return ResourceManager.GetString("PleasefilltheHomepagefield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string Pleasefillthenamefield {
            get {
                return ResourceManager.GetString("Pleasefillthenamefield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleaseFilltheQuestionFiled {
            get {
                return ResourceManager.GetString("PleaseFilltheQuestionFiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string Pleasefilltheshortnamefield {
            get {
                return ResourceManager.GetString("Pleasefilltheshortnamefield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string Pleasefilltitlefield {
            get {
                return ResourceManager.GetString("Pleasefilltitlefield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleasefillValidDatefield {
            get {
                return ResourceManager.GetString("PleasefillValidDatefield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleasefillVenuNamefield {
            get {
                return ResourceManager.GetString("PleasefillVenuNamefield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string PleasefillZipCodefield {
            get {
                return ResourceManager.GetString("PleasefillZipCodefield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in to continue..
        /// </summary>
        internal static string Pleasesignintocontinue {
            get {
                return ResourceManager.GetString("Pleasesignintocontinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poster.
        /// </summary>
        internal static string Poster {
            get {
                return ResourceManager.GetString("Poster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poster Email ID.
        /// </summary>
        internal static string PosterEmailID {
            get {
                return ResourceManager.GetString("PosterEmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting Date.
        /// </summary>
        internal static string PostingDate {
            get {
                return ResourceManager.GetString("PostingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string ProfilePage {
            get {
                return ResourceManager.GetString("ProfilePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro Musician.
        /// </summary>
        internal static string ProMusician {
            get {
                return ResourceManager.GetString("ProMusician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q &amp; A.
        /// </summary>
        internal static string QA {
            get {
                return ResourceManager.GetString("QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Shop.
        /// </summary>
        internal static string RepairShop {
            get {
                return ResourceManager.GetString("RepairShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertory.
        /// </summary>
        internal static string Repertory {
            get {
                return ResourceManager.GetString("Repertory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        internal static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporter.
        /// </summary>
        internal static string Reporter {
            get {
                return ResourceManager.GetString("Reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        internal static string Seemore {
            get {
                return ResourceManager.GetString("Seemore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Name.
        /// </summary>
        internal static string ShopName {
            get {
                return ResourceManager.GetString("ShopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Owner.
        /// </summary>
        internal static string ShopOwner {
            get {
                return ResourceManager.GetString("ShopOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name.
        /// </summary>
        internal static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since Year.
        /// </summary>
        internal static string SinceYear {
            get {
                return ResourceManager.GetString("SinceYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponser.
        /// </summary>
        internal static string Sponser {
            get {
                return ResourceManager.GetString("Sponser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject/Theme.
        /// </summary>
        internal static string SubjectTheme {
            get {
                return ResourceManager.GetString("SubjectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Title.
        /// </summary>
        internal static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Professor.
        /// </summary>
        internal static string TeacherProfessor {
            get {
                return ResourceManager.GetString("TeacherProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel No.
        /// </summary>
        internal static string TelNo {
            get {
                return ResourceManager.GetString("TelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of use.
        /// </summary>
        internal static string Termsofuse {
            get {
                return ResourceManager.GetString("Termsofuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThisWeek.
        /// </summary>
        internal static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Box.
        /// </summary>
        internal static string TicketBox {
            get {
                return ResourceManager.GetString("TicketBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        internal static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter URL.
        /// </summary>
        internal static string TwitterURL {
            get {
                return ResourceManager.GetString("TwitterURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe.
        /// </summary>
        internal static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Info.
        /// </summary>
        internal static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Date.
        /// </summary>
        internal static string ValidDate {
            get {
                return ResourceManager.GetString("ValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue.
        /// </summary>
        internal static string Venue {
            get {
                return ResourceManager.GetString("Venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venu Name.
        /// </summary>
        internal static string VenuName {
            get {
                return ResourceManager.GetString("VenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What kind Of User Are you?.
        /// </summary>
        internal static string WhatkindOfUserAreyou {
            get {
                return ResourceManager.GetString("WhatkindOfUserAreyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Affilation.
        /// </summary>
        internal static string YourAffilation {
            get {
                return ResourceManager.GetString("YourAffilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
