//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PerformanceTbl()
        {
            this.PerformanceMusicianInstrumentTbls = new HashSet<PerformanceMusicianInstrumentTbl>();
        }
    
        public int PerformanceID { get; set; }
        public string MainTitle { get; set; }
        public string SubTitle { get; set; }
        public string Subject { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Time { get; set; }
        public int Region { get; set; }
        public int City { get; set; }
        public int Venue { get; set; }
        public string PosterFileName { get; set; }
        public string VideoFileName { get; set; }
        public string TicketBox { get; set; }
        public int PerformanceGroup { get; set; }
        public int PerformanceType { get; set; }
        public Nullable<int> Conductor { get; set; }
        public Nullable<int> MainTitleComposer { get; set; }
        public Nullable<int> MainInstrument { get; set; }
        public string Organizer { get; set; }
        public string Sponser { get; set; }
        public string Language { get; set; }
        public string Program { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime UpdateTimeStamp { get; set; }
        public Nullable<System.DateTime> ArchivingTimeStamp { get; set; }
    
        public virtual InstrumentTbl InstrumentTbl { get; set; }
        public virtual VenueTbl VenueTbl { get; set; }
        public virtual LookUpTbl LookUpTbl { get; set; }
        public virtual LookUpTbl LookUpTbl1 { get; set; }
        public virtual LookUpTbl LookUpTbl2 { get; set; }
        public virtual MusicianTbl MusicianTbl { get; set; }
        public virtual MusicianTbl MusicianTbl1 { get; set; }
        public virtual PerformanceGroupTbl PerformanceGroupTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerformanceMusicianInstrumentTbl> PerformanceMusicianInstrumentTbls { get; set; }
        public virtual UserTbl UserTbl { get; set; }
    }
}
