//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswersTbl
    {
        public int AnswerID { get; set; }
        public string Answer { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    
        public virtual QuestionsTbl QuestionsTbl { get; set; }
        public virtual UserTbl UserTbl { get; set; }
    }
}
