//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleTbl
    {
        public int ArticleID { get; set; }
        public string ArticleURL { get; set; }
        public string PosterEmailID { get; set; }
        public System.DateTime UpdateTimeStamp { get; set; }
    }
}
