//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditionTbl
    {
        public int AuditionID { get; set; }
        public string Organizer { get; set; }
        public string Title { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string AuditionOutline { get; set; }
        public string PosterEmailID { get; set; }
        public System.DateTime UpdateTimeStamp { get; set; }
    }
}
