//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeTbl
    {
        public int CollegeID { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string HomePage { get; set; }
        public string Country { get; set; }
        public string CollegePhoto { get; set; }
        public string LocationMap { get; set; }
        public string Introduction { get; set; }
        public System.DateTime UpdateTimeStamp { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual UserTbl UserTbl { get; set; }
    }
}
