//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConcourTbl
    {
        public int ConcourID { get; set; }
        public string Organizer { get; set; }
        public string Title { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string ConcourOutline { get; set; }
        public System.DateTime UpdateTimeStamp { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual UserTbl UserTbl { get; set; }
    }
}
