//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessP
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicianEndorserTbl
    {
        public int ID { get; set; }
        public string EndorserName { get; set; }
        public string EndorserEmail { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public Nullable<System.DateTime> EndorsedDate { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
