//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessP
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionsTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionsTbl()
        {
            this.AnswersTbls = new HashSet<AnswersTbl>();
        }
    
        public int QuestionID { get; set; }
        public string Question { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswersTbl> AnswersTbls { get; set; }
        public virtual UserTbl UserTbl { get; set; }
    }
}
